apiVersion: v2
name: demo
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: v1.0.0

dependencies:
  - name: demo
    repository: http://harbor.zili.work/chartrepo/charts
    version: 1.0.0
